name: Code Quality check

on:
  pull_request:
    branches: "**"
    paths:
      - "app/**"
    users:
      - "dependabot[bot]"
  workflow_dispatch:
jobs:
  code_quality_check:
    runs-on: ubuntu-latest
    steps:
      - name: 🛫 Checkout code
        uses: actions/checkout@v4

      - name: 🏗 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: "npm"
          cache-dependency-path: ./app/package-lock.json

      - name: ⚙️ NPM install
        run: npm ci
        working-directory: ./app

      - name: ⚙️ Run lint
        run: npm run lint
        working-directory: ./app

      - name: 🧹Format code
        run: npm run format-check
        working-directory: ./app

      - name: type check
        run: npm run type-check
        working-directory: ./app
