// Barrel of every ABI wrapper in this folder. Generated once; keep in sync
// with the wrapper files. The version-aware resolver (registry.ts) imports it.
export * from './ad-campaign-manager'
export * from './bank'
export * from './board-of-directors'
export * from './bod'
export * from './cash-remuneration-eip712'
export * from './elections'
export * from './erc20'
export * from './expense-account'
export * from './expense-account-eip712'
export * from './factory-beacon'
export * from './fixed-return'
export * from './investors'
export * from './officer'
export * from './ownable-pausable'
export * from './proposals'
export * from './safe-deposit-router'
export * from './vesting'
export * from './voting'
